# Generated by Django 3.0.8 on 2020-11-03 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('review', models.CharField(max_length=500)),
                ('weapon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon')),
            ],
        ),
    ]
