# Generated by Django 3.0.8 on 2020-08-17 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_auto_20200816_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
