# Generated by Django 3.0.8 on 2020-11-03 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0002_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='weapon',
        ),
    ]
