# Generated by Django 3.0.8 on 2020-11-03 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0003_remove_review_weapon'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='weapon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon'),
        ),
    ]
