# Generated by Django 3.0.8 on 2020-11-08 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0004_review_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='weapon',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon'),
        ),
    ]
