# Generated by Django 3.0.8 on 2020-11-21 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0005_auto_20201108_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='weapon',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon'),
        ),
    ]
