# Generated by Django 3.0.8 on 2020-11-21 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0007_auto_20201121_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='weapon',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='weapons.Weapon'),
        ),
    ]
