# Generated by Django 3.0.8 on 2020-12-13 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weapons', '0011_auto_20201123_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='weapons.Category'),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='image_url',
            field=models.URLField(default=0, max_length=1024),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='manufacture',
            field=models.CharField(default=0, max_length=254),
        ),
    ]
