# Generated by Django 3.0.8 on 2020-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='redeem_key',
            field=models.CharField(default='', editable=False, max_length=25),
        ),
    ]
