# Generated by Django 3.0.8 on 2020-09-27 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_redeem_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='redeem_key',
        ),
    ]
